

export const setupCommands = [
	`gamerule commandblockoutput false`,
	`gamerule doimmediaterespawn true`,
	`gamerule dolimitedcrafting true`,
	`gamerule keepinventory true`,
	`gamerule pvp false`,
	`gamerule randomtickspeed 2`,
	`gamerule recipesunlock true`,
	`gamerule showbordereffect true`,
	`gamerule showcoordinates true`,
	`gamerule showrecipemessages true`,
	`gamerule showtags true`,
	`gamerule spawnradius 0`,
	`scoreboard objectives add totalLives dummy "§d§lIMAGINARY"`,
	`scoreboard objectives add totalJumps dummy `,
	`scoreboard objectives setdisplay sidebar totalLives descending`,
	`tickingarea add circle 0 100 0 4 si`,
	`scoreboard objectives add totalTotems dummy`
];

export const listItemsCooldown = [
	"minecraft:wooden_axe",
	"minecraft:wooden_hoe",
	"minecraft:wooden_pickaxe",
	"minecraft:wooden_shovel",
	"minecraft:wooden_sword",
	"minecraft:stone_axe",
	"minecraft:stone_hoe",
	"minecraft:stone_pickaxe",
	"minecraft:stone_shovel",
	"minecraft:stone_sword",
	"minecraft:golden_axe",
	"minecraft:golden_hoe",
	"minecraft:golden_pickaxe",
	"minecraft:golden_shovel",
	"minecraft:golden_sword",
	"minecraft:diamond_axe",
	"minecraft:diamond_hoe",
	"minecraft:diamond_pickaxe",
	"minecraft:diamond_shovel",
	"minecraft:diamond_sword",
	"minecraft:netherite_axe",
	"minecraft:netherite_hoe",
	"minecraft:netherite_pickaxe",
	"minecraft:netherite_shovel",
	"minecraft:netherite_sword",
	"minecraft:fishing_rod",
	"minecraft:bow",
	"minecraft:crossbow",
	"minecraft:shears",
	"minecraft:flint_and_steel",
	"minecraft:trident",
	"minecraft:spyglass",
	"minecraft:brush",
	"ha:healing_center",
	"minecraft:shears"
];
